train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/public_c/crl/ref/data/cod/TrainDataset/Image
      root_path_2: /home/ubuntu/public_c/crl/ref/data/cod/TrainDataset/GT
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
#      inp_size: 1024
      inp_size: 1008
      augment: false
  batch_size: 2

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/public_c/crl/ref/data/cod/TestDataset/Image
      root_path_2: /home/ubuntu/public_c/crl/ref/data/cod/TestDataset/GT
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
#      inp_size: 1024
      inp_size: 1008
  batch_size: 2

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/public_c/crl/ref/data/ISTD_Dataset/test/test_A
      root_path_2: /home/ubuntu/public_c/crl/ref/data/ISTD_Dataset/test/test_B
#       root_path_1: /home/ubuntu/public_c/crl/ref/data/cod/TestData_new/cod10k/Image
#      root_path_1: /home/ubuntu/public_c/crl/ref/data/cod/TestDataset/Image
#      root_path_1: /home/ubuntu/public_c/crl/ref/data/kvasir-seg/test/images
#      root_path_2: /home/ubuntu/public_c/crl/ref/data/kvasir-seg/test/masks
#      root_path_2: /home/ubuntu/public_c/crl/ref/data/cod/TestData_new/cod10k/GT
#      root_path_2: /home/ubuntu/public_c/crl/ref/data/cod/TestDataset/GT
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
#      inp_size: 1024
      inp_size: 1008
  batch_size: 1

eval_type: ber
sam_checkpoint: /home/ubuntu/public_c/crl/sam3_adapter/checkpoint/sam3.pt
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam
  args:
#    inp_size: 1024
    inp_size: 1008
    loss: iou
    encoder_mode:
      name: sam
#      img_size: 1024
      img_size: 1008
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1024
      depth: 24
      num_heads: 16
      global_attn_indexes:
      - 5
      - 11
      - 17
      - 23
optimizer:
  name: adamw
  args:
    lr: 0.0002
lr_min: 1.0e-7
epoch_max: 100

multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1

resume: 0
#start_epoch: 60
