train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/img/trainw
      root_path_2: ./load/masks/trainw
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 1024
      augment: false
      interpolation_mode: "nearest"
      resampling_factor: 1
      resampling_inp_size: 1024
  batch_size: 1

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/kandelaki/bt/data_20/preprocessed/256/load/img/eval
      root_path_2: /home/kandelaki/bt/data_20/preprocessed/256/load/masks/eval
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
      interpolation_mode: "nearest"
      resampling_factor: 2
      resampling_inp_size: 256
  batch_size: 1

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/kandelaki/bt/data_20/preprocessed/256/load/img/test
      root_path_2: /home/kandelaki/bt/data_20/preprocessed/256/load/masks/test
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
      interpolation_mode: "nearest"
      resampling_factor: 2
      resampling_inp_size: 1024
  batch_size: 1

infer_dataset:
  dataset:
    name: image-folder
    args:
      path: /home/kandelaki/git/SAM-Adapter-PyTorch/forward_folder
  wrapper:
    name: infer
    args:
      inp_size: 1024
      interpolation_mode: "nearest"
      resampling_factor: 1
      resampling_inp_size: 1024
  batch_size: 1

eval_type: f1
sam_checkpoint: ./pretrained/sam_vit_b_01ec64.pth
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam
  args:
    inp_size: 1024
    loss: iou
    device: cpu
    encoder_mode:
      name: sam
      img_size: 1024
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 768
      depth: 12
      num_heads: 12
      global_attn_indexes:
      - 2
      - 5
      - 8
      - 11
optimizer:
  name: adamw
  args:
    lr: 0.0002
lr_min: 1.0e-7
epoch_max: 1

multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1

# For basic logging
log_dir: ./save_resampled_4_on_factor_4/
# For Tensorboard
write_dir: ./save_resampled_4_on_factor_4/
#resume: 1
#start_epoch: 1
